---

- name: Retrive password from Cyberark
  delegate_to: localhost
  uri:
    url: "https://{{ cyberark_settings.host }}/AIMWebService/api/Accounts?AppID={{ cyberark_settings.app_id }}&Safe={{ item.value.cyberark_safe }}&Username={{ item.key }}"
    # validate_certs: no
  when: service_accounts is defined and cyberark_settings is defined and item.value.cyberark_safe is defined
  loop: "{{ query('dict', service_accounts|default({})) }}"
  register: cyberark_output
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord
  no_log: true

- name: Update service account variable
  set_fact:
    service_accounts: "{{ service_accounts | combine({sa_out.item.key: {'password': sa_out.json.Content}}) }}"
  loop: "{{ cyberark_output.results|flatten(levels=1) }}"
  loop_control:
    loop_var: sa_out
  when: service_accounts is defined and sa_out.failed is defined and not sa_out.failed and sa_out.status is defined and sa_out.status==200
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord
  no_log: true
