---
- name: get password from pmp
  delegate_to: localhost
  run_once: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    PMP_URL: "{{ pmp_settings.pmp_url }}"
    PMP_AUTHTOKEN: "{{ pmp_settings.pmp_authtoken }}"
    RESOURCENAME: "{{ pmp_settings.resourcename }}"
    ACCOUNTNAME: "{{ pmp_settings.accountname }}"
  set_fact:
    pmp_pwd: "{{ query('pmp.pmp.passwordmanagerpro', RESOURCENAME, ACCOUNTNAME, PMP_URL, PMP_AUTHTOKEN)[0] }}"
  when: service_accounts is defined and pmp_settings is defined and item.value.cyberark_safe is defined
  loop: "{{ query('dict', service_accounts|default({})) }}"
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord
  no_log: true

- name: Update service account variable
  set_fact:
    service_accounts: "{{ service_accounts | combine({'uddos_device_admin': {'password': pmp_pwd}}, recursive=True) }}"
  when: pmp_pwd is defined
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord
  no_log: true

