---
# Build config for Arista EOS

- name: apply config commands
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o userknownhostsfile=/dev/null'
  eos_config:
    lines:
    - "{{ item }}"
  connection: network_cli
  with_items:
    - ["{{ config_cmds }}"]
  tags:
  - never
  - eos_config
  register: result

- name: save config
  import_tasks: save_config.yml
  tags:
  - never
  - eos_config
