---
# Build config for Juniper JUNOS

- name: get password from pmp
  include_tasks: ../../iac.common/tasks/pmp_get_password.yml
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord
  
- name: change service account password
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o userknownhostsfile=/dev/null'
  junos_user:
    name: "{{ item.key }}"
    role: super-user
    encrypted_password: "{{ item.value.password | password_hash('sha512') }}"
    state: present
  # don't change password for the account that runs the ansible task
  when: item.value.password is defined
  loop: "{{ query('dict', service_accounts|default({})) }}"
  connection: netconf
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord
  register: my_output
  #no_log: true  

- name: save config
  import_tasks: save_config.yml
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord

- name: switch to the device local login user
  set_fact:
    ansible_user: "{{ item.key }}"
    ansible_password: "{{ item.value.password }}"
  when: item.value.password is defined
  loop: "{{ query('dict', service_accounts|default({})) }}"
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord
  register: my_output
  #no_log: true

- name: confirm login as device local login user with new password
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o userknownhostsfile=/dev/null'
  junos_command:
    commands: show log messages
    display: json
  connection: netconf
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord
  register: result

- name: device log confirmation of new password login
  debug:
    msg: "{{ result.stdout[0]['file-content'][0]['data'].split('\n')[-5:] | select('search','Accepted password for {0}'.format(ansible_user)) | list }}"
  tags:
  - never
  - chAnGe_ServIce_AccOunT_PassWord 


